from tkinter import *
def donothing():
    filewin = Toplevel(top)
    button = Button(filewin, text="Do nothing button")
    button.pack()
    
top = Tk()
top.title("Notepad")
top.geometry("600x600")
T = Text(top, height=60, width=200)
T.pack()
T.insert(END, "Hello World\nNaluebet Manpati\nComputer Science\nNo.583120100125\n")
T.insert(END, "RMU")

menubar = Menu(top)
filemenu = Menu(menubar , tearoff = 0)
filemenu.add_command(label = "New",command = donothing)
filemenu.add_command(label = "Open",command = donothing)
filemenu.add_command(label = "Save",command = donothing)
filemenu.add_command(label = "Save As...",command = donothing)
filemenu.add_separator()
filemenu.add_command(label = "Page Setup...",command = donothing)
filemenu.add_command(label = "Print...",command = donothing)
filemenu.add_separator()
filemenu.add_command(label = "Exit",command = donothing)
menubar.add_cascade(label = "File",menu = filemenu)

editmenu = Menu(menubar, tearoff = 0)
editmenu.add_command(label = "Undo",command = donothing)
editmenu.add_separator()
editmenu.add_command(label = "Cut",command = donothing)
editmenu.add_command(label = "Coppy",command = donothing)
editmenu.add_command(label = "Paste",command = donothing)
editmenu.add_command(label = "Delete",command = donothing)
editmenu.add_separator()
editmenu.add_command(label = "Find...",command = donothing)
editmenu.add_command(label = "Find Next",command = donothing)
editmenu.add_command(label = "Replace...",command = donothing)
editmenu.add_command(label = "Go To...",command = donothing)
editmenu.add_separator()
editmenu.add_command(label = "Select All",command = donothing)
editmenu.add_command(label = "Time/Dete",command = donothing)
menubar.add_cascade(label = "Edit", menu = editmenu)

formatmenu = Menu(menubar, tearoff = 0)
formatmenu.add_command(label = "Word Wrap",command = donothing)
formatmenu.add_command(label = "Font...",command = donothing)
menubar.add_cascade(label = "Format", menu = formatmenu)

viewmenu = Menu(menubar, tearoff = 0)
viewmenu.add_command(label = "Status Bar",command = donothing)
menubar.add_cascade(label = "View", menu = viewmenu)

helpmenu = Menu(menubar, tearoff = 0)
helpmenu.add_command(label = "View Help",command = donothing)
helpmenu.add_separator()
helpmenu.add_command(label = "About Notepad",command = donothing)
menubar.add_cascade(label = "Help", menu = helpmenu)

top.config(menu = menubar)
top.mainloop()